language: csharp
solution: visualuiaverify.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore visualuiaverify.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll
